blog:
  source:
    path: /Users/lzwjava/projects/blog-source
  default:
    model: mistralai/mistral-7b-instruct:free

openrouter:
  api:
    key: ${OPENROUTER_API_KEY:}
    url: https://openrouter.ai/api/v1/chat/completions
