blog:
  source:
    path: /Users/lzwjava/projects/blog-source
  default:
    model: google/gemini-3-flash-preview

openrouter:
  api:
    key: ${OPENROUTER_API_KEY:}
    url: https://openrouter.ai/api/v1/chat/completions

github:
  token: ${GITHUB_PAT_TOKEN:}
